package main

const (
	If       = "if"
	Else     = "else"
	For      = "for"
	Func     = "func"
	LParen   = "("
	RParen   = ")"
	LBrace   = "{"
	RBrace   = "}"
	Int      = "int"
	Double   = "double"
	Return   = "return"
	Plus     = "+"
	Minus    = "-"
	Multi    = "*"
	Divide   = "/"
	Assign   = "="
	Less     = "<"
	Great    = ">"
	LessEq   = "<="
	GreateEq = ">="
	Equal    = "=="
	NotEq    = "!="
	Space    = " "
	CmtSlash = "//"
)
